import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './Navbar';
import Footer from './Footer';
// import Sidebar from './Sidebar'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Baganime',
  description: 'Generated by Me',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="{inter.className} bg-cyan-100">
        {/* <SessionProvider */}
        <Navbar />
        {children}
        {/*<Sidebar />*/}

        <Footer />
      </body>
    </html>
  );
}
